# Docker file for UMD User Interface
#
FROM aaroc/ansiblecontainer:centos7
MAINTAINER Bruce Becker <bbecker@csir.co.za>
RUN ansible-playbook -c local -i /etc/ansible/hosts worker-nodes.yml --skip-tags="slack"
